### ISSUE TITLE
Error about Program failed to complete

### ISSUE THREAD

**Issue by Manuel-yang** [emredurgunlu/Anchor-Metaplex-NFT#1]
Hi I tried to deploy your project on localnet but It throwed an error about 

`     Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
      at Connection.sendEncodedTransaction (node_modules/@solana/web3.js/src/connection.ts:5024:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Connection.sendRawTransaction (node_modules/@solana/web3.js/src/connection.ts:4983:20)
      at sendAndConfirmRawTransaction (node_modules/@project-serum/anchor/src/provider.ts:288:21)
      at AnchorProvider.sendAndConfirm (node_modules/@project-serum/anchor/src/provider.ts:148:14)
      at MethodsBuilder.rpc [as _rpcFn] (node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:29:16)`

I don't think there is anything wrong about the code, but I can't figure it out
Thanks if you can reply me

**Comment by emredurgunlu** [comment]
Hi. I had deployed that project on the devnet

So in the Anchor.toml file:
[registry]
url = "https://api.apr.dev"
[provider]
cluster = "devnet".

However, if you are working on a local network, the Anchor.toml file should contain:
[provider]
cluster = "localnet"

(see https://www.anchor-lang.com/docs/manifest)

You can use the config set --url command to change the RPC URL:
solana config set --url localhost
or
solana config set --url http://localhost:8899

To see which Cluster you're currently targeting:
solana config get

In a separate window / terminal, you need to run "solana-test-validator" so that the tools can talk to your local network.


Please take a look at these sites:
https://docs.solana.com/developing/test-validator
https://stackoverflow.com/questions/71582268/solana-anchor-framework-cant-connect-to-localhost-and-therefor-not-deply-to-it
